import Navigation from "./Navigation";
import Head from 'next/head'

function Header() {


    return ( 
        <>
        
         <Head>
            <title>Tea-Corner</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo_tea.png" />
         </Head>
       
        <Navigation/>
        
        </>
     );
}

export default Header;